---
- hosts: ansible

  tasks:
    - name: create docker image
      command: docker build -t regapp:latest .
      args:
        chdir: /opt/docker
    - name: create tag to push image to docker hub
      command: docker tag regapp:latest shehanhasanga/regapp:latest
    - name: push docker image
      command: docker push shehanhasanga/regapp:latest
