---
- hosts: kubernetes
  user: root
  tasks:
    - name: deploy regapp to kubernetes
      command: kubectl apply -f /root/regapp-deployment.yml
    - name: deploy reg app into services
      command: kubectl apply -f /root/regapp-service.yml
